pub fun echo_info(msg: Text): Null {
    trust $ tput bold; tput setaf 4; echo "{msg}"; tput sgr0 $
}

pub fun echo_success(msg: Text): Null {
    trust $ tput bold; tput setaf 2; echo "{msg}"; tput sgr0 $
}

pub fun echo_warning(msg: Text): Null {
    trust $ tput bold; tput setaf 3; echo "{msg}"; tput sgr0 $
}

pub fun echo_error(msg: Text): Null {
    trust $ tput bold; tput setaf 1; echo "{msg}" >&2; tput sgr0 $
}
