title: " git "
items:

  - NoDim:
      name: "Folder #[fg=green]$(echo ${PWD##*/})"

  - NoDim:
      name: "Branch #[fg=green]$(git rev-parse --abbrev-ref HEAD)"

  - Seperate: {}

  - Menu:
      name: "tig"
      shortcut: g
      command: _gen-close-hook tig && tig
      session: true
      session_name: "tig"
      session_on_dir: true
      run_on_git_root: true
      environment:
        MENU_POPUP: "1"
        NO_WINDOW_MGNT: "1"

      position:
        w: 140
        h: 80

  - Menu:
      name: "gitui"
      shortcut: u
      command: _gen-close-hook gitui && gitui
      session: true
      session_name: "gitui"
      session_on_dir: true
      run_on_git_root: true
      environment:
        MENU_POPUP: "1"
        NO_WINDOW_MGNT: "1"

      position:
        w: 140
        h: 80

  - Menu:
      name: "gh dash"
      shortcut: d
      command: _gen-close-hook gh-dash && gh dash
      session: true
      session_name: "gh-dash"
      session_on_dir: true
      run_on_git_root: true
      environment:
        MENU_POPUP: "1"
        NO_WINDOW_MGNT: "1"

      position:
        w: 150
        h: 80

  - Menu:
      name: "Git branch"
      shortcut: b
      command: $CONFIG/tmux/menu/scripts/gitbranch.sh
      background: true

  - Seperate: {}

  - Menu:
      name: "dump gitignore"
      shortcut: i
      command: "gibo dump %%LANGUAGE%% | less && gibo dump %%LANGUAGE%% | pbcopy"

      inputs:
        - LANGUAGE

      position:
        w: 150
        h: 80
