#!/bin/sh

init_tmux() {
    tmux new-session -d -e MAIN_POPUP=1 -e DEFAULT=1 -s popup 2>/dev/null
    tmux -u new-session -e MAIN=1 -e DEFAULT=1 -s main 2>/dev/null

    # Reset status on startup
    rm -f /tmp/tmux-popup-loc.json
}

cd "$HOME" || exit 1
init_tmux || tmux -u attach -t main
