return {
	cmd = { "harper-ls", "--stdio" },
	root_markers = require("modules.constant").root_markers,
	filetypes = {
		"gitcommit",
		"python",
		"markdown",
		"text",
		"latex",
		"tex",
		"html",
		"xml",
		"json",
		"yaml",
		"toml",
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact",
		"vue",
		"css",
		"scss",
		"less",
		"php",
		"ruby",
		"go",
		"rust",
		"hcl",
		"terraform",
		"shell",
		"bash",
		"fish",
		"powershell",
		"sql",
		"lua",
		"elixir",
		"erlang",
		"swift",
		"kotlin",
		"java",
		"c",
		"cpp",
		"csharp",
		"objective-c",
		"dart",
	},
	settings = {
		["harper-ls"] = {
			userDictPath = "",
			fileDictPath = "",
			linters = {
				SpellCheck = true,
				SpelledNumbers = false,
				AnA = true,
				SentenceCapitalization = true,
				UnclosedQuotes = true,
				WrongQuotes = true,
				LongSentences = false,
				RepeatedWords = true,
				Spaces = true,
				Matcher = false,
				CorrectNumberSuffix = true,
			},
			codeActions = {
				ForceStable = false,
			},
			markdown = {
				IgnoreLinkTitle = false,
			},
			isolateEnglish = false,
			dialect = "American",
		},
	},
}
