-- if require('modules.plugin').mark_as_loaded('octo') then
--   return
-- end

-- require"octo".setup({
--   use_local_fs = false,                    -- use local files on right side of reviews
--   enable_builtin = false,                  -- shows a list of builtin actions when no action is provided
--   default_remote = {"upstream", "origin"}, -- order to try remotes
--   default_merge_method = "commit",         -- default merge method which should be used for both `octo pr merge` and merging from picker, could be `commit`, `rebase` or `squash`
--   default_delete_branch = false,           -- whether to delete branch when merging pull request with either `octo pr merge` or from picker (can be overridden with `delete`/`nodelete` argument to `octo pr merge`)
--   ssh_aliases = {},                        -- ssh aliases. e.g. `ssh_aliases = {["github.com-work"] = "github.com"}`. the key part will be interpreted as an anchored lua pattern.
--   picker = "telescope",                    -- or "fzf-lua"
--   picker_config = {
--     use_emojis = false,                    -- only used by "fzf-lua" picker for now
--     mappings = {                           -- mappings for the pickers
--       open_in_browser = { lhs = "<c-b>", desc = "open issue in browser" },
--       copy_url = { lhs = "<c-y>", desc = "copy url to system clipboard" },
--       checkout_pr = { lhs = "<c-o>", desc = "checkout pull request" },
--       merge_pr = { lhs = "<c-r>", desc = "merge pull request" },
--     },
--   },
--   comment_icon = "▎",                      -- comment marker
--   outdated_icon = "󰅒 ",                    -- outdated indicator
--   resolved_icon = " ",                    -- resolved indicator
--   reaction_viewer_hint_icon = " ",        -- marker for user reactions
--   commands = {},                           -- additional subcommands made available to `octo` command
--   users = "search",                        -- users for assignees or reviewers. values: "search" | "mentionable" | "assignable"
--   user_icon = " ",                        -- user icon
--   ghost_icon = "󰊠 ",                       -- ghost icon
--   timeline_marker = " ",                  -- timeline marker
--   timeline_indent = "2",                   -- timeline indentation
--   right_bubble_delimiter = "",            -- bubble delimiter
--   left_bubble_delimiter = "",             -- bubble delimiter
--   github_hostname = "",                    -- github enterprise host
--   snippet_context_lines = 4,               -- number or lines around commented lines
--   gh_cmd = "gh",                           -- command to use when calling github cli
--   gh_env = {},                             -- extra environment variables to pass on to github cli, can be a table or function returning a table
--   timeout = 5000,                          -- timeout for requests between the remote server
--   default_to_projects_v2 = false,          -- use projects v2 for the `octo card ...` command by default. both legacy and v2 commands are available under `octo cardlegacy ...` and `octo cardv2 ...` respectively.
--   ui = {
--     use_signcolumn = false,                -- show "modified" marks on the sign column
--     use_signstatus = true,                 -- show "modified" marks on the status column
--   },
--   issues = {
--     order_by = {                           -- criteria to sort results of `octo issue list`
--       field = "created_at",                -- either comments, created_at or updated_at (https://docs.github.com/en/graphql/reference/enums#issueorderfield)
--       direction = "desc"                   -- either desc or asc (https://docs.github.com/en/graphql/reference/enums#orderdirection)
--     }
--   },
--   reviews = {
--     auto_show_threads = true,              -- automatically show comment threads on cursor move
--     focus             = "right",           -- focus right buffer on diff open
--   },
--   pull_requests = {
--     order_by = {                           -- criteria to sort the results of `octo pr list`
--       field = "created_at",                -- either comments, created_at or updated_at (https://docs.github.com/en/graphql/reference/enums#issueorderfield)
--       direction = "desc"                   -- either desc or asc (https://docs.github.com/en/graphql/reference/enums#orderdirection)
--     },
--     always_select_remote_on_create = false -- always give prompt to select base remote repo when creating prs
--   },
--   notifications = {
--     current_repo_only = false,             -- show notifications for current repo only
--   },
--   file_panel = {
--     size = 10,                             -- changed files panel rows
--     use_icons = true                       -- use web-devicons in file panel (if false, nvim-web-devicons does not need to be installed)
--   },
--   colors = {                               -- used for highlight groups (see colors section below)
--     white = "#ffffff",
--     grey = "#2a354c",
--     black = "#000000",
--     red = "#fdb8c0",
--     dark_red = "#da3633",
--     green = "#acf2bd",
--     dark_green = "#238636",
--     yellow = "#d3c846",
--     dark_yellow = "#735c0f",
--     blue = "#58a6ff",
--     dark_blue = "#0366d6",
--     purple = "#6f42c1",
--   },
--   mappings_disable_default = false,        -- disable default mappings if true, but will still adapt user mappings
--   mappings = {
--     issue = {
--       close_issue = { lhs = "<localleader>ic", desc = "close issue" },
--       reopen_issue = { lhs = "<localleader>io", desc = "reopen issue" },
--       list_issues = { lhs = "<localleader>il", desc = "list open issues on same repo" },
--       reload = { lhs = "<c-r>", desc = "reload issue" },
--       open_in_browser = { lhs = "<c-b>", desc = "open issue in browser" },
--       copy_url = { lhs = "<c-y>", desc = "copy url to system clipboard" },
--       add_assignee = { lhs = "<localleader>aa", desc = "add assignee" },
--       remove_assignee = { lhs = "<localleader>ad", desc = "remove assignee" },
--       create_label = { lhs = "<localleader>lc", desc = "create label" },
--       add_label = { lhs = "<localleader>la", desc = "add label" },
--       remove_label = { lhs = "<localleader>ld", desc = "remove label" },
--       goto_issue = { lhs = "<localleader>gi", desc = "navigate to a local repo issue" },
--       add_comment = { lhs = "<localleader>ca", desc = "add comment" },
--       delete_comment = { lhs = "<localleader>cd", desc = "delete comment" },
--       next_comment = { lhs = "]c", desc = "go to next comment" },
--       prev_comment = { lhs = "[c", desc = "go to previous comment" },
--       react_hooray = { lhs = "<localleader>rp", desc = "add/remove 🎉 reaction" },
--       react_heart = { lhs = "<localleader>rh", desc = "add/remove ❤️ reaction" },
--       react_eyes = { lhs = "<localleader>re", desc = "add/remove 👀 reaction" },
--       react_thumbs_up = { lhs = "<localleader>r+", desc = "add/remove 👍 reaction" },
--       react_thumbs_down = { lhs = "<localleader>r-", desc = "add/remove 👎 reaction" },
--       react_rocket = { lhs = "<localleader>rr", desc = "add/remove 🚀 reaction" },
--       react_laugh = { lhs = "<localleader>rl", desc = "add/remove 😄 reaction" },
--       react_confused = { lhs = "<localleader>rc", desc = "add/remove 😕 reaction" },
--     },
--     pull_request = {
--       checkout_pr = { lhs = "<localleader>po", desc = "checkout pr" },
--       merge_pr = { lhs = "<localleader>pm", desc = "merge commit pr" },
--       squash_and_merge_pr = { lhs = "<localleader>psm", desc = "squash and merge pr" },
--       rebase_and_merge_pr = { lhs = "<localleader>prm", desc = "rebase and merge pr" },
--       list_commits = { lhs = "<localleader>pc", desc = "list pr commits" },
--       list_changed_files = { lhs = "<localleader>pf", desc = "list pr changed files" },
--       show_pr_diff = { lhs = "<localleader>pd", desc = "show pr diff" },
--       add_reviewer = { lhs = "<localleader>va", desc = "add reviewer" },
--       remove_reviewer = { lhs = "<localleader>vd", desc = "remove reviewer request" },
--       close_issue = { lhs = "<localleader>ic", desc = "close pr" },
--       reopen_issue = { lhs = "<localleader>io", desc = "reopen pr" },
--       list_issues = { lhs = "<localleader>il", desc = "list open issues on same repo" },
--       reload = { lhs = "<c-r>", desc = "reload pr" },
--       open_in_browser = { lhs = "<c-b>", desc = "open pr in browser" },
--       copy_url = { lhs = "<c-y>", desc = "copy url to system clipboard" },
--       goto_file = { lhs = "gf", desc = "go to file" },
--       add_assignee = { lhs = "<localleader>aa", desc = "add assignee" },
--       remove_assignee = { lhs = "<localleader>ad", desc = "remove assignee" },
--       create_label = { lhs = "<localleader>lc", desc = "create label" },
--       add_label = { lhs = "<localleader>la", desc = "add label" },
--       remove_label = { lhs = "<localleader>ld", desc = "remove label" },
--       goto_issue = { lhs = "<localleader>gi", desc = "navigate to a local repo issue" },
--       add_comment = { lhs = "<localleader>ca", desc = "add comment" },
--       delete_comment = { lhs = "<localleader>cd", desc = "delete comment" },
--       next_comment = { lhs = "]c", desc = "go to next comment" },
--       prev_comment = { lhs = "[c", desc = "go to previous comment" },
--       react_hooray = { lhs = "<localleader>rp", desc = "add/remove 🎉 reaction" },
--       react_heart = { lhs = "<localleader>rh", desc = "add/remove ❤️ reaction" },
--       react_eyes = { lhs = "<localleader>re", desc = "add/remove 👀 reaction" },
--       react_thumbs_up = { lhs = "<localleader>r+", desc = "add/remove 👍 reaction" },
--       react_thumbs_down = { lhs = "<localleader>r-", desc = "add/remove 👎 reaction" },
--       react_rocket = { lhs = "<localleader>rr", desc = "add/remove 🚀 reaction" },
--       react_laugh = { lhs = "<localleader>rl", desc = "add/remove 😄 reaction" },
--       react_confused = { lhs = "<localleader>rc", desc = "add/remove 😕 reaction" },
--       review_start = { lhs = "<localleader>vs", desc = "start a review for the current pr" },
--       review_resume = { lhs = "<localleader>vr", desc = "resume a pending review for the current pr" },
--       resolve_thread = { lhs = "<localleader>rt", desc = "resolve pr thread" },
--       unresolve_thread = { lhs = "<localleader>rt", desc = "unresolve pr thread" },
--     },
--     review_thread = {
--       goto_issue = { lhs = "<localleader>gi", desc = "navigate to a local repo issue" },
--       add_comment = { lhs = "<localleader>ca", desc = "add comment" },
--       add_suggestion = { lhs = "<localleader>sa", desc = "add suggestion" },
--       delete_comment = { lhs = "<localleader>cd", desc = "delete comment" },
--       next_comment = { lhs = "]c", desc = "go to next comment" },
--       prev_comment = { lhs = "[c", desc = "go to previous comment" },
--       select_next_entry = { lhs = "]q", desc = "move to next changed file" },
--       select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
--       select_first_entry = { lhs = "[q", desc = "move to first changed file" },
--       select_last_entry = { lhs = "]q", desc = "move to last changed file" },
--       close_review_tab = { lhs = "<c-c>", desc = "close review tab" },
--       react_hooray = { lhs = "<localleader>rp", desc = "add/remove 🎉 reaction" },
--       react_heart = { lhs = "<localleader>rh", desc = "add/remove ❤️ reaction" },
--       react_eyes = { lhs = "<localleader>re", desc = "add/remove 👀 reaction" },
--       react_thumbs_up = { lhs = "<localleader>r+", desc = "add/remove 👍 reaction" },
--       react_thumbs_down = { lhs = "<localleader>r-", desc = "add/remove 👎 reaction" },
--       react_rocket = { lhs = "<localleader>rr", desc = "add/remove 🚀 reaction" },
--       react_laugh = { lhs = "<localleader>rl", desc = "add/remove 😄 reaction" },
--       react_confused = { lhs = "<localleader>rc", desc = "add/remove 😕 reaction" },
--       resolve_thread = { lhs = "<localleader>rt", desc = "resolve pr thread" },
--       unresolve_thread = { lhs = "<localleader>rt", desc = "unresolve pr thread" },
--     },
--     submit_win = {
--       approve_review = { lhs = "<c-a>", desc = "approve review", mode = { "n", "i" } },
--       comment_review = { lhs = "<c-m>", desc = "comment review", mode = { "n", "i" } },
--       request_changes = { lhs = "<c-r>", desc = "request changes review", mode = { "n", "i" } },
--       close_review_tab = { lhs = "<c-c>", desc = "close review tab", mode = { "n", "i" } },
--     },
--     review_diff = {
--       submit_review = { lhs = "<localleader>vs", desc = "submit review" },
--       discard_review = { lhs = "<localleader>vd", desc = "discard review" },
--       add_review_comment = { lhs = "<localleader>ca", desc = "add a new review comment", mode = { "n", "x" } },
--       add_review_suggestion = { lhs = "<localleader>sa", desc = "add a new review suggestion", mode = { "n", "x" } },
--       focus_files = { lhs = "<localleader>e", desc = "move focus to changed file panel" },
--       toggle_files = { lhs = "<localleader>b", desc = "hide/show changed files panel" },
--       next_thread = { lhs = "]t", desc = "move to next thread" },
--       prev_thread = { lhs = "[t", desc = "move to previous thread" },
--       select_next_entry = { lhs = "]q", desc = "move to next changed file" },
--       select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
--       select_first_entry = { lhs = "[q", desc = "move to first changed file" },
--       select_last_entry = { lhs = "]q", desc = "move to last changed file" },
--       close_review_tab = { lhs = "<c-c>", desc = "close review tab" },
--       toggle_viewed = { lhs = "<localleader><space>", desc = "toggle viewer viewed state" },
--       goto_file = { lhs = "gf", desc = "go to file" },
--     },
--     file_panel = {
--       submit_review = { lhs = "<localleader>vs", desc = "submit review" },
--       discard_review = { lhs = "<localleader>vd", desc = "discard review" },
--       next_entry = { lhs = "j", desc = "move to next changed file" },
--       prev_entry = { lhs = "k", desc = "move to previous changed file" },
--       select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
--       refresh_files = { lhs = "r", desc = "refresh changed files panel" },
--       focus_files = { lhs = "<localleader>e", desc = "move focus to changed file panel" },
--       toggle_files = { lhs = "<localleader>b", desc = "hide/show changed files panel" },
--       select_next_entry = { lhs = "]q", desc = "move to next changed file" },
--       select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
--       select_first_entry = { lhs = "[q", desc = "move to first changed file" },
--       select_last_entry = { lhs = "]q", desc = "move to last changed file" },
--       close_review_tab = { lhs = "<c-c>", desc = "close review tab" },
--       toggle_viewed = { lhs = "<localleader><space>", desc = "toggle viewer viewed state" },
--     },
--     notification = {
--       read = { lhs = "<localleader>rn", desc = "mark notification as read" },
--     },
--   },
-- })
